### model
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: Qwen2.5-32B-Instruct_mix_mathematic_problems_ds-format #open_r1_cot_length_6k #qwen-14b-medium-cot #
template: deepseek3
cutoff_len: 4096 #2048 #8192
max_samples: 2000 #10000 #10000
overwrite_cache: true
preprocessing_num_workers: 16
# packing: true

### output
output_dir: ../models/Deepseek-Qwen-7B/Deepseek-Qwen-7B-Short-COT
logging_steps: 2
save_strategy: "epoch"
plot_loss: true
overwrite_output_dir: true
save_only_model: true

### train
per_device_train_batch_size: 4 #1 #2 #1
gradient_accumulation_steps: 2 #8 #4 #8
learning_rate: 1.0e-5
num_train_epochs: 1.0 # 2.0
lr_scheduler_type: constant #cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
max_grad_norm: 10

### eval
val_size: 0.0001
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50000

### optimization
flash_attn: fa2
enable_liger_kernel: true

